version: "3.7"
services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - backend
      - db
    volumes:
      - ./src:/usr/app/src
    networks:
      - common
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/src:/root/src
    networks:
      - common
  db:
    image: mongo
    networks:
      - common
networks:
  common:
