version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - backend
      - db
    networks:
      - common
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - common
  db:
    image: mongo
    networks:
      - common
networks:
  common:

